# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
# Basic dependabot.yml file with
# minimum configuration for two package managers

version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  # Dependabot for root
  - package-ecosystem: "npm"
    directory: "/"
    reviewers:
      - "theaccordance"
    schedule:
      interval: "weekly"

  # Dependabot for strapi
  - package-ecosystem: "npm"
    directory: "/packages/strapi"
    ignore:
      - dependency-name: "passport"
    reviewers:
      - "theaccordance"
    schedule:
      interval: "weekly"

  # Dependabot for Ionic
  - package-ecosystem: "npm"
    directory: "/packages/ionic"
    reviewers:
      - "theaccordance"
    schedule:
      interval: "weekly"


