parameters: {}
environment: {}
functions:
  - name: cerebro
    binary: false
    main: ""
    runtime: nodejs:default
    web: true
    parameters: { }
    environment: { }
    annotations: { }
    limits: { }

