parameters: {}
environment: {}
packages:
  - name: slack
    shared: false
    environment: { }
    parameters: { }
    annotations: { }
    functions:
      - name: cerebro
        binary: false
        main: ""
        runtime: nodejs:default
        web: true
        webSecure: false
        parameters: {}
        environment: {}
        annotations: {}
        limits: {}
