# Documentation: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions
on: pull_request
jobs:
  build:
    name: "Build Application"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm ci
      - run: npm build


