# Documentation: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions

on:
  push:
    branches:
      - master
    paths:
      - 'config/**'
      - 'src/**'
      - 'package.json'
  workflow_dispatch:
jobs:
  deploy:
    name: "Deploy API Application to Digital Ocean"
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - uses: actions/checkout@v3
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - env:
          APP_ID: ${{ secrets.DIGITALOCEAN_APP_ID }}
        run: doctl apps create-deployment $APP_ID

