# Documentation: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions
name: "Strapi: Deploy API"
on:
  push:
    branches:
      - main
    paths:
      - 'apps/strapi/config/**'
      - 'apps/strapi/src/**'
      - 'apps/strapi/package.json'
  workflow_dispatch:
jobs:
  deploy:
    name: "Deploy API Application to Digital Ocean"
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - uses: actions/checkout@v4
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - run: doctl apps create-deployment f684eb04-5a28-427f-85f6-bb9e2b6c5326

